name: Commit pytest logs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  create_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest and save log
        run: python -m pytest > log_pytest.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git add log_pytest.txt
          git commit -m "Add pytest log from workflow" || echo "No changes to commit"
          git push
